spring:
  datasource:
    url: jdbc:mysql://localhost:3306/likelion_kakao
    username: root
    password: '0310'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: dlrkdmsdlaa00@gmail.com
    password: ryxwxioiaivsrlqx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo1NDMyMTBhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5eg=="
  access-token-validity-in-milliseconds: 3600000

kakao:
  client-id: 7345a824544e6ebdd36d08bdbf88aa3c
  client-secret: ""
  redirect-uri: http://localhost:8080/login/oauth2/code/kakao
  token-url: https://kauth.kakao.com/oauth/token
  user-info-url: https://kapi.kakao.com/v2/user/me

token:
  expire:
    time: 1800000
